spring.application.name=HaveAnIdea

spring.datasource.url=jdbc:mysql://localhost:3306/have_an_idea
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.ai.ollama.chat.model=llama3.2:3b
#Bu sat?r Spring AI kütüphanesinin, senin bilgisayar?nda çal??an Ollama sunucusuna ba?lan?p hangi modeli kullanaca??n? söylemesini sa?lar.
#Ekstra olarak chatclient bunu okur ve buna özel bir bean olu?turur ve istenen i?lemleri yapabilir